name: airport
description: An application for the airport.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  rxdart: ^0.27.2
  states_rebuilder: ^6.0.0
  intl: ^0.17.0
  dio: ^4.0.6
  cached_network_image: ^3.1.0+1
  freezed_annotation: ^2.0.1
  flutter_local_notifications: ^9.5.3+1
  timezone: ^0.8.0
  hive: ^2.2.1
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.10
  freezed: ^2.0.2
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/bgs/
    - assets/company_icons/
    - assets/warning_images/
